### PR TITLE
Update 3.1.2

### LINKED ISSUE #7: update to version 3.1.2

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #7

### CODE REVIEW

**Comment by pelson** [comment]
With the following changes, I'm able to get it to compile on OSX:

```

diff --git a/recipe/build.sh b/recipe/build.sh
index 5831aba..96da611 100644
--- a/recipe/build.sh
+++ b/recipe/build.sh
@@ -1,7 +1,6 @@
 #!/bin/bash
 
-export CFLAGS="-I$PREFIX/include $CFLAGS"
-
+export CFLAGS="-Wl,-U,_MO_syslog -I$PREFIX/include $CFLAGS" 
 mkdir build && cd build
 
 cmake -D CMAKE_INSTALL_PREFIX=$PREFIX \
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index a1baeeb..7ad4c06 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
 
@@ -22,7 +23,7 @@ requirements:
 
 test:
   commands:
-    - test -f ${PREFIX}/lib/libmo_unpack.so  # [not win]
+    - test -f ${PREFIX}/lib/libmo_unpack.so  # [linux]
     - conda inspect linkages -p $PREFIX libmo_unpack  # [not win]
     - conda inspect objects -p $PREFIX libmo_unpack  # [osx]
```

I also needed to change the source:

```
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index 7629e0b..9568d22 100644RARIES} mo_unpack m rt pthread)
--- a/tests/CMakeLists.txtLIBRARIES} mo_unpack m pthread)
+++ b/tests/CMakeLists.txtsrc)
@@ -2,7 +2,7 @@ enable_testing()le.c)
 find_package(Check REQUIRED)le ${LIBS})
 include_directories(${CMAKE_INCLUDE_PATH})
 include_directories(${CHECK_INCLUDE_DIRS})
-set(LIBS ${LIBS} ${CHECK_LIBRARIES} mo_unpack m rt pthread)
+set(LIBS ${LIBS} ${CHECK_LIBRARIES} mo_unpack m pthread)
 include_directories(. ../src)
 add_executable(test_rle check_rle.c)
 target_link_libraries(test_rle ${LIBS})
```

I'm probably going to park this for now, but wanted to report my progress.

**Comment by pelson** [comment]
I also double checked that the changes allow mo_pack to continue to build also on OSX, so appears to have no detrimental effect. 🎉

**Comment by ocefpaf** [comment]
@pelson can you review and merge if you are OK with the changes here?

**Comment by pelson** [comment]
Holy smokes. Great stuff @ocefpaf! 👼 
Looks great to me.

**Pull request merged**
